sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t villuriram/docker-react -f Dockerfile.dev .

scritp:
  - docker run villuriram/docker-react npm run test -- --coverage
